---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-pttg-rps-api
  labels:
    version: {{.VERSION}}
spec:
  replicas: 2
  selector:
    matchLabels:
      name: kube-pttg-rps-api
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: kube-pttg-rps-api
        version: {{.VERSION}}
      annotations:
        pod.beta.kubernetes.io/init-containers: '
[
   {
      "name": "vaultjks",
      "image": "quay.io/ukhomeofficedigital/vaultjks:v0.1.0",
      "imagePullPolicy": "Always",
      "env": [
         {
            "name": "VAULT_ADDR",
            "value": "https://vault.vault.svc.cluster.local:8200"
         },
         {
            "name": "VAULT_TOKEN",
            "valueFrom": {
               "secretKeyRef": {
                  "name": "store-token",
                  "key": "token"
               }
            }
         },
         {
            "name": "VAULT_PKI_PATH",
            "value": "services/pt-i-{{.ENVIRONMENT}}/pki"
         },
         {
            "name": "VAULT_ROLE_NAME",
            "value": "default"
         },
         {
            "name": "SLEEP_FOREVER",
            "value": "false"
         },
         {
            "name": "IP_SAN",
            "valueFrom": {
               "fieldRef": {
                  "apiVersion": "v1",
                  "fieldPath": "status.podIP"
               }
            }
         }
      ],
      "volumeMounts": [
         {
            "mountPath": "/data",
            "name": "javapki"
         }
      ]
   }
]
        '
    spec:
      containers:
      - name: vault-sidekick
        image: quay.io/ukhomeofficedigital/vault-sidekick:v0.2.0
        imagePullPolicy: Always
        resources:
         limits:
          memory: "100Mi"
          cpu: 100m
         requests:
          memory: "50Mi"
          cpu: 100m
        args:
          - -output=/etc/nginx/secrets
          - -tls-skip-verify=true
          - -cn=pki:services/${NAMESPACE}/pki/issue/default:common_name=kube-pttg-rps-api.${NAMESPACE}.svc.cluster.local,file=/etc/nginx/secrets/kube-pttg-rps-api,fmt=bundle
        env:
          - name: VAULT_ADDR
            value: "https://vault.vault.svc.cluster.local:8200"
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: VAULT_TOKEN
            valueFrom:
              secretKeyRef:
                name: store-token
                key: token
        volumeMounts:
          - mountPath: /etc/nginx/secrets
            name: secrets
      - name: proxy
        image: quay.io/ukhomeofficedigital/pttg-nginx-proxy:v3.1.3a
        imagePullPolicy: Always
        resources:
         limits:
          memory: "100Mi"
          cpu: 100m
         requests:
          memory: "50Mi"
          cpu: 100m
        env:
          - name: PROXY_SERVICE_HOST
            value: '127.0.0.1'
          - name: PROXY_SERVICE_PORT
            value: '8080'
          - name: NAXSI_USE_DEFAULT_RULES
            value: 'FALSE'
          - name: ENABLE_UUID_PARAM
            value: 'FALSE'
          - name: HTTPS_REDIRECT
            value: 'FALSE'
          - name: SERVER_CERT
            value: /etc/nginx/secrets/kube-pttg-rps-api-bundle.pem
          - name: SERVER_KEY
            value: /etc/nginx/secrets/kube-pttg-rps-api-key.pem
        volumeMounts:
          - name: secrets
            mountPath: /etc/nginx/secrets
            readOnly: true
        ports:
          - name: https
            containerPort: 10443
      - name: kube-pttg-rps-api
        image: quay.io/ukhomeofficedigital/kube-pttg-rps-api:{{.VERSION}}
        env:
          - name: JAVA_OPTS
            value: '-Xms150m -Xmx250m -Djavax.net.ssl.trustStore=/data/truststore.jks'
          - name: SERVER_PORT
            value: '8080'
          - name: ENDPOINTS_INFO_ENABLED
            value: 'false'
          - name: SPRING_PROFILES_ACTIVE
            value: 'postgres'
          - name: PTTG_DB_HOSTNAME
            valueFrom:
              secretKeyRef:
                name: pttg-rds-access
                key: endpoint
          - name: PTTG_DB_PORT
            valueFrom:
              secretKeyRef:
                name: pttg-rds-access
                key: port
          - name: PTTG_DB_NAME
            valueFrom:
              secretKeyRef:
                name: pttg-rds-access
                key: database
          - name: IP_SCHEMA_NAME
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: schema_name
          - name: IP_DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: application_username
          - name: IP_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: application_password
          - name: HRMC_SERVICE_URL
            value: "https://pttg-ip-hmrc.pt-i-{{.ENVIRONMENT}}.svc.cluster.local"
          - name: JDK_TRUST_FILE
            value: '/data/truststore.jks'
          - name: AUDITING_DEPLOYMENT_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: AUDITING_DEPLOYMENT_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: SYSDIG_ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                name: sysdig-secrets
                key: token
          - name: SYSDIG_SERVICE_URL
            valueFrom:
              configMapKeyRef:
                name: endpoint-config
                key: BASE_SYSDIG_URL
        resources:
          limits:
            cpu: 1600m
            memory: 612Mi
          requests:
            cpu: 100m
            memory: 484Mi
        ports:
          - name: http
            containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
            httpHeaders:
              - name: X-probe
                value: kubelet
          initialDelaySeconds: 10
          periodSeconds: 20
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
            httpHeaders:
              - name: X-probe
                value: kubelet
          initialDelaySeconds: 10
          periodSeconds: 20
          timeoutSeconds: 10
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /data
            name: javapki
            readOnly: true
      volumes:
      - name: secrets
        emptyDir:
          medium: "Memory"
      - name: javapki
        emptyDir:
          medium: "Memory"
      - name: keycloak-api-secret
        secret:
          secretName: keycloak-api-secret
